### PR TITLE
New Launcher Icon

### PR DESCRIPTION
**Pull request by SyNtheticNightmar3**
Create a "flat" icon to go with Android's new Material Design.
PNGs made using GIMP and Android's Roboto font; optimized using OptiPNG + pngquant.

I can mess with the design if there are any ideas for improvement. :)

### CODE REVIEW

**Comment by NadyaNayme** [comment]
I like this. :+1:

**Comment by Blackburn29** [comment]
Thanks for this SyN. funny to see you around in somewhere other than android kernel development;)

**Comment by SyNtheticNightmar3** [comment]
I could say the same for you lol. What is the best method of contacting you?

**Comment by Blackburn29** [comment]
perimeter2929 -> gmail
Can be reached via email or hangouts

**Pull request merged**
